const data = {
  products: [
    {
      name: "Think And Grow Rich",
      slug: "Think-And-Grow_Rich",
      image: "/imagess/tagh.png",
      price: 120,
      countInStock: 10,
      writer: "Nepolian Hill",
      rating: 4.5,
      numReviews: 10,
      description: "self help and motivational book",
    },
    {
      name: "Alchemist",
      slug: "Alchemist",
      image: "/imagess/alchemist.jpeg",
      price: 150,
      countInStock: 20,
      writer: "Paulo Coelho",
      rating: 4,
      numReviews: 7,
      description: "story of the great person",
    },
    {
      name: "Steve Jobs",
      slug: "steve-jobs",
      image: "/imagess/steve.jpeg",
      price: 200,
      countInStock: 15,
      writer: "Walter Isaacson",
      rating: 4.7,
      numReviews: 3,
      description: "biography of apple ceo steve jobs",
    },
    {
      name: "Think Like a Monk",
      slug: "think-like-a-monk",
      image: "/imagess/tlam.jpeg",
      price: 300,
      countInStock: 40,
      writer: "Jay Sheety",
      rating: 4.2,
      numReviews: 26,
      description: "a book to help people to implement the life of the monk",
    },
  ],
};
export default data;
